import Footer from "./components/Footer";
import "./globals.css";
import localFont from "next/font/local";
import { Montserrat, Open_Sans } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-opensans",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${openSans.variable} ${montserrat.variable}`}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
