import Footer from "./components/Footer";
import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cfont = localFont({
  src: "../public/font/font.ttf",
  variable: "--font-cfont",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cfont.variable}`}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
